/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as LauncherRouteImport } from './routes/launcher'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as LoopsIndexRouteImport } from './routes/loops.index'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as LoopsLoopIdRouteImport } from './routes/loops.$loopId'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherRoute = LauncherRouteImport.update({
  id: '/launcher',
  path: '/launcher',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopsIndexRoute = LoopsIndexRouteImport.update({
  id: '/loops/',
  path: '/loops/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopsLoopIdRoute = LoopsLoopIdRouteImport.update({
  id: '/loops/$loopId',
  path: '/loops/$loopId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launcher': typeof LauncherRoute
  '/new': typeof NewRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/loops/$loopId': typeof LoopsLoopIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/loops/': typeof LoopsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launcher': typeof LauncherRoute
  '/new': typeof NewRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/loops/$loopId': typeof LoopsLoopIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/boards': typeof BoardsIndexRoute
  '/loops': typeof LoopsIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/launcher': typeof LauncherRoute
  '/new': typeof NewRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/loops/$loopId': typeof LoopsLoopIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/loops/': typeof LoopsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launcher'
    | '/new'
    | '/boards/$boardId'
    | '/loops/$loopId'
    | '/sessions/$sessionId'
    | '/boards/'
    | '/loops/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/launcher'
    | '/new'
    | '/boards/$boardId'
    | '/loops/$loopId'
    | '/sessions/$sessionId'
    | '/boards'
    | '/loops'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/launcher'
    | '/new'
    | '/boards/$boardId'
    | '/loops/$loopId'
    | '/sessions/$sessionId'
    | '/boards/'
    | '/loops/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LauncherRoute: typeof LauncherRoute
  NewRoute: typeof NewRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  LoopsLoopIdRoute: typeof LoopsLoopIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
  LoopsIndexRoute: typeof LoopsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher': {
      id: '/launcher'
      path: '/launcher'
      fullPath: '/launcher'
      preLoaderRoute: typeof LauncherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loops/': {
      id: '/loops/'
      path: '/loops'
      fullPath: '/loops/'
      preLoaderRoute: typeof LoopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loops/$loopId': {
      id: '/loops/$loopId'
      path: '/loops/$loopId'
      fullPath: '/loops/$loopId'
      preLoaderRoute: typeof LoopsLoopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LauncherRoute: LauncherRoute,
  NewRoute: NewRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  LoopsLoopIdRoute: LoopsLoopIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  BoardsIndexRoute: BoardsIndexRoute,
  LoopsIndexRoute: LoopsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
