export const keys = {
  health: ['health'] as const,
  sidebarSessions: ['sessions', 'sidebar'] as const,
  allSessions: ['sessions', 'all'] as const,
  archivedSessions: ['sessions', 'archived'] as const,
  sessionMessages: (id: string) => ['sessions', id, 'messages'] as const,
  sessionRepo: (id: string) => ['sessions', id, 'repo'] as const,
  sessionEvents: (id: string) => ['sessions', id, 'events'] as const,
  agentFiles: ['agent', 'files'] as const,
  agentSettings: ['settings', 'agents'] as const,
  memory: ['memory'] as const,
  mcpServers: ['mcp', 'servers'] as const,
  acpAgents: ['acp', 'agents'] as const,
  openRouterModels: ['openrouter', 'models'] as const,
  workspaceDirs: (path: string) => ['workspace', 'dirs', path] as const,
  workspaceFiles: (root: string) => ['workspace', 'files', root] as const,
  skills: ['skills'] as const,
  loops: ['loops'] as const,
  loopDetail: (id: string) => ['loops', id] as const,
  boards: ['boards'] as const,
  boardDetail: (id: string) => ['boards', id] as const,
}
