package visualize

import (
	"context"
	"errors"

	"github.com/wins/jaz/backend/internal/tools"
	visualizesvc "github.com/wins/jaz/backend/internal/visualize"
)

type ReadMeTool struct{}

type ShowWidgetTool struct{}

func (ReadMeTool) Definition() tools.Definition {
	return tools.Function(
		visualizesvc.ReadMeToolName,
		"Loads Claude-compatible inline artifact guidance before creating an SVG or HTML artifact with the provider-safe visualize_show_widget alias. Call this silently before the first visual artifact in a turn.",
		false,
		tools.ObjectSchema(map[string]any{
			"modules": map[string]any{
				"type":        "array",
				"description": "Guidance modules to load.",
				"items": map[string]any{
					"type": "string",
					"enum": []string{"diagram", "mockup", "interactive", "data_viz", "art", "chart", "elicitation"},
				},
			},
			"platform": map[string]any{
				"type":        "string",
				"description": "Target surface size.",
				"enum":        []string{"mobile", "desktop", "unknown"},
			},
		}, []string{}),
	)
}

func (ReadMeTool) Execute(context.Context, map[string]any) (tools.Result, error) {
	return tools.Result{Content: visualizesvc.ReadMeGuide}, nil
}

func (ShowWidgetTool) Definition() tools.Definition {
	return tools.Function(
		visualizesvc.ShowWidgetToolName,
		"Renders an inline SVG, HTML fragment, or bundled HTML document in the Jaz transcript. Call visualize_read_me first in the turn.",
		false,
		tools.ObjectSchema(map[string]any{
			"loading_messages": map[string]any{
				"type":        "array",
				"description": "One to four short status messages while rendering.",
				"items":       map[string]any{"type": "string"},
				"minItems":    1,
				"maxItems":    4,
			},
			"title":       tools.StringSchema("Short artifact title."),
			"widget_code": tools.StringSchema("Raw SVG, HTML fragment, or full self-contained HTML document. For React artifacts, pass bundled HTML generated by the web-artifacts-builder skill."),
		}, []string{"loading_messages", "title", "widget_code"}),
	)
}

func (ShowWidgetTool) Execute(_ context.Context, inputs map[string]any) (tools.Result, error) {
	messages, err := stringSlice(inputs["loading_messages"])
	if err != nil {
		return tools.Result{}, err
	}
	output, _, err := visualizesvc.BuildArtifact(visualizesvc.ShowWidgetInput{
		LoadingMessages: messages,
		Title:           tools.StringInput(inputs, "title"),
		WidgetCode:      tools.StringInput(inputs, "widget_code"),
	})
	if err != nil {
		return tools.Result{}, err
	}
	return tools.JSONResult(output)
}

func stringSlice(value any) ([]string, error) {
	items, ok := value.([]any)
	if !ok {
		return nil, errors.New("loading_messages is required")
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		text, ok := item.(string)
		if !ok {
			return nil, errors.New("loading_messages must contain strings")
		}
		out = append(out, text)
	}
	return out, nil
}
